### ISSUE TITLE
Let's integrate with React!

### ISSUE THREAD

**Issue by sniper365** [tirth-2001/express-typescript-vercel-part2#1]
Hi @tirth-2001 
Simple and great code!

Btw let's imagine to integrate with React

Ofc It's working with only standalone Express(ts). I am integrating with React(ts). Working on local env. But it showed me up the error while deploying to vercel

Here is the details;

![image](https://user-images.githubusercontent.com/30114178/218528809-cb1424d0-11ad-45c5-86a9-15f390366953.png)

index.ts
```
import dotenv from "dotenv";
import express, { Express, Request, Response } from "express";
import path from "path";
import cors from "cors";

dotenv.config();

const app: Express = express();

app.use(express.json());
app.use(cors());

app.use(express.static(path.join(__dirname, '../client/build')));

app.get('/*', (req: Request, res: Response) => {
  res.sendFile(path.join(__dirname, '../client/build', 'index.html'));
});

const port = process.env.PORT || 8000;

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
```

vercel.json
```
{
	"version": 2,
	"builds": [
		{
			"src": "dist/index.js",
			"use": "@vercel/node",
			"config": { "includeFiles": ["dist/**"] }
		}
	],
	"routes": [
		{
			"src": "/(.*)",
			"dest": "dist/index.js"
		}
	]
}
```

tsconfig.json
```
{
	"compilerOptions": {
	  "target": "es2016",
	  "jsx": "preserve",
	  "module": "commonjs",
	  "allowJs": true,
	  "outDir": "./dist",
	  "esModuleInterop": true,
	  "forceConsistentCasingInFileNames": true,
	  "strict": true,
	  "skipLibCheck": true
	},
	"exclude": [
	  "client",
	  "dist",
	  "node_modules"
	]
  }
```

the error when deploy to vercel; it showed up the Not Found.. 

![image](https://user-images.githubusercontent.com/30114178/218529409-cbc5eebc-3c4a-44db-a126-e8f3ea491bb7.png)

![image](https://user-images.githubusercontent.com/30114178/218529504-7c28db6f-a1f6-4d39-b610-0729f043776e.png)

![image](https://user-images.githubusercontent.com/30114178/218529924-f965c748-9ac0-4f3e-90a8-6bfe18dbe38e.png)

Could you let me know if anything is wrong?

**Comment by tirth-2001** [comment]
Hi @sniper365 . I'm unable to catch up on your exact requirement. As per my understanding, there can be 2 scenarios you are trying to get done
1. Deploy react app to Vercel
2. Deploy express API on Vercel, and then use it in react app.

Can you please clarify your requirement so that jointly we can plan out an efficient solution?

**Comment by sniper365** [comment]
Hey @tirth-2001 

Thanks for reply
I did on my side somehow.
Added react(ts) app and let the express server render their build file

Thank you
